### ISSUE TITLE
Version 2.3.0 doesn't work

### ISSUE THREAD

**Issue by lroige** [OpenFlutter/flutter_screenutil#136]
Me and a coworker have found this error in separate computers. When updating to 2.3.0 (and adding context to the initialization of screenUtil) we get the following error:

```flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building MyApp(dirty, state: _MyAppState#67dd7):
flutter: MediaQuery.of() called with a context that does not contain a MediaQuery.
flutter: No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
flutter: This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
flutter: a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
flutter: The context used was:
flutter:   MyApp
flutter:
flutter: The relevant error-causing widget was:
flutter:   MyApp file:///Users/user/Documents/Project/lib/main.dart:9:23
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:813:5)
flutter: #1      ScreenUtil.init (package:flutter_screenutil/screenutil.dart:46:44)
flutter: #2      _MyAppState.build (package:flutterbaseproject/main.dart:34:16)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
flutter: #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
flutter: #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
flutter: #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
flutter: #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
flutter: #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1119:5)
flutter: #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1061:17)
flutter: #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
flutter: #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1060:13)
flutter: #17     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
flutter: #18     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
flutter: (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building MyApp(dirty, state: _MyAppState#67dd7):
MediaQuery.of() called with a context that does not contain a MediaQuery.

No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of(). This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
The context used was: MyApp
  dirty
  state: _MyAppState#67dd7
The relevant error-causing widget was: 
  MyApp file:///Users/user/Documents/Project/lib/main.dart:9:23
When the exception was thrown, this was the stack: 
#0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:813:5)
#1      ScreenUtil.init (package:flutter_screenutil/screenutil.dart:46:44)
#2      _MyAppState.build (package:project/main.dart:34:16)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```
We are using the last version of Flutter and didn't make any other change when updating the library. For now our solution is to fix the version to 2.2.0.

**Comment by lizhuoyuan** [comment]
Don't initialize outside myapp

**Comment by lizhuoyuan** [comment]
#134

**Comment by lroige** [comment]
Thank you, I'll try that
