### ISSUE TITLE
error after upgrade to flutter 3.0

### ISSUE THREAD

**Issue by azizkandias01** [OpenFlutter/flutter_screenutil#393]
i got error after upgrade to flutter 3.0

`======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder(dependencies: [MediaQuery]):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4864 pos 12: 'child == _child': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Builder Builder:file:///Users/zeekands/.pub-cache/hosted/pub.dartlang.org/flutter_screenutil-5.5.2/lib/src/screenutil_init.dart:109:16
When the exception was thrown, this was the stack: 
#2      ComponentElement.forgetChild (package:flutter/src/widgets/framework.dart:4864:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3752:14)
...     Normal element mounting (301 frames)
#304    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#305    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#306    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (405 frames)
#711    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#712    Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#713    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1202:16)
#714    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1171:5)
#715    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1119:18)
#716    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
#717    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1118:13)
#718    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:953:7)
#719    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:933:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================
W/Gralloc3(15955): mapper 3.x is not supported

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.

The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
- [GlobalObjectKey int#675e6]
This was determined by noticing that after the widget with the above global key was moved out of its previous parent, that previous parent never updated during this frame, meaning that it either did not update at all or updated before the widget was moved, in either case implying that it still thinks that it should have a child with that global key.
The specific parent that did not update after having one or more children forcibly removed due to GlobalKey reparenting is:
- Builder(dependencies: [MediaQuery])
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2991:15)
#1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3016:8)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:893:19)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================
`

**Comment by dovahkrid** [comment]
get the same error too

**Comment by azizkandias01** [comment]
hi, this is how i initialize the library 

`ScreenUtilInit(
      designSize: designSize,
      builder: (context) => Scaffold(......)`
in flutter it was working fine.

**Comment by Mounir-Bouaiche** [comment]
> 

How many times you use ScreenUtilInit() ?

**Comment by Mounir-Bouaiche** [comment]
@azizkandias01 make sure you use ScreenUtilInit once in your app, and initialize it as documentation says.
```dart
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    //Set the fit size (Find your UI design, look at the dimensions of the device screen and fill it in,unit in dp)
    return ScreenUtilInit(
      designSize: const Size(360, 690),
      minTextAdapt: true,
      splitScreenMode: true,
      builder: (child) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          title: 'First Method',
          // You can use the library anywhere in the app even in theme
          theme: ThemeData(
            primarySwatch: Colors.blue,
            textTheme: Typography.englishLike2018.apply(fontSizeFactor: 1.sp),
          ),
          home: child,
        );
      },
      child: const HomePage(title: 'First Method'),
    );
  }
}
```

**Comment by arbile26** [comment]
The same!

**Comment by Mounir-Bouaiche** [comment]
Friends, this is not the manner how we discuss an issue. You must provide more details and codes to be able to reproduce and debug this error. Thank you.

**Comment by arbile26** [comment]
@Mounir-Bouaiche 
Everything was OK, just updated to Flutter 3, when I build an appbundle or run the app it prints on the console:
```
Building with sound null safety 💪

/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_screenutil-5.3.1/lib/screenutil_init.dart:23:54: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
      data: MediaQueryData.fromWindow(WidgetsBinding.instance!.window),
                                                     ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/extension_navigation.dart:357:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/extension_navigation.dart:468:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/snackbar/snackbar.dart:452:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback(
                     ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/rx_flutter/rx_disposable.dart:20:22: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/rx_flutter/rx_notifier.dart:130:22: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/simple/get_controllers.dart:90:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/simple/get_controllers.dart:96:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/router_report.dart:53:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/measured_size-1.0.0/lib/measured_size.dart:29:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback(postFrameCallback);
                     ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/measured_size-1.0.0/lib/measured_size.dart:35:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback(postFrameCallback);
                     ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/scroll_to_index-2.1.1/lib/scroll_to_index.dart:358:57: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
  Future _waitForWidgetStateBuild() => SchedulerBinding.instance!.endOfFrame;
                                                        ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/back_button_interceptor-5.0.2/lib/src/back_button_interceptor.dart:29:74: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
  static Future<void> Function() handlePopRouteFunction = WidgetsBinding.instance!.handlePopRoute;
                                                                         ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/back_button_interceptor-5.0.2/lib/src/back_button_interceptor.dart:32:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.handlePushRoute as Future<void> Function(String?);
                     ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/better_player-0.0.81/lib/src/core/better_player.dart:66:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/better_player-0.0.81/lib/src/core/better_player.dart:113:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/custom_pop_up_menu-1.2.3+1/lib/src/custom_pop_up_menu.dart:195:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((call) {
                   ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.4.1/lib/flutter_web_auth.dart:33:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(_resumedObserver); // safety measure so we never add this observer twice
                   ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.4.1/lib/flutter_web_auth.dart:34:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addObserver(_resumedObserver);
                   ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.4.1/lib/flutter_web_auth.dart:47:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(_resumedObserver);
                   ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/image_cropping-0.0.11/lib/image_cropping.dart:240:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((timeStamp) async {
                     ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.4.2+2/lib/src/widgets/selectable.dart:459:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:126:28: Warning: Operand of null-aware operation '?.' has type 'RendererBinding' which excludes null.
 - 'RendererBinding' is from 'package:flutter/src/rendering/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/rendering/binding.dart').
    assert(RendererBinding.instance?.renderView != null);
                           ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:127:50: Warning: Operand of null-aware operation '!' has type 'RendererBinding' which excludes null.
 - 'RendererBinding' is from 'package:flutter/src/rendering/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/rendering/binding.dart').
    var clipRect = Offset.zero & RendererBinding.instance!.renderView.size;
                                                 ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:170:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((timeStamp) {
                         ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:193:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!
                     ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.4.2+2/lib/src/widgets/selection/overlay_manager.dart:138:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      if (SchedulerBinding.instance!.schedulerPhase ==
                           ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.4.2+2/lib/src/widgets/selection/overlay_manager.dart:140:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!
                         ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.4.2+2/lib/src/widgets/selection/web_selection_manager.dart:119:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!
                       ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.4.2+2/lib/src/widgets/selection/overlay.dart:141:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    if (SchedulerBinding.instance!.schedulerPhase ==
                         ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.4.2+2/lib/src/widgets/selection/overlay.dart:143:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback(_markNeedsBuild);
                       ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.4.2+2/lib/src/widgets/selection/overlay.dart:193:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    if (SchedulerBinding.instance!.schedulerPhase ==
                         ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.4.2+2/lib/src/widgets/selection/overlay.dart:195:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback(_markNeedsBuild);
                       ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_widget_from_html_core-0.8.5+1/lib/src/widgets/html_table.dart:592:26: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
          WidgetsBinding.instance
                         ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_widget_from_html_core-0.8.5+1/lib/src/widgets/html_table.dart:606:28: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
            WidgetsBinding.instance
                           ^
/Users/yusifjasim/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_widget_from_html_core-0.8.5+1/lib/src/internal/ops/anchor.dart:120:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/Users/yusifjasim/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback(
                   ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by Mounir-Bouaiche** [comment]
@arbile26 Those are not errors, in flutter 3.0.0, WidgetsBinding.instance couldn't be null anymore so we shouldn't use null aware operators (?,!,??,...). All packages in your app prints same info (and not error).

**Comment by azizkandias01** [comment]
> > hi, this is how i initialize the library
> > `ScreenUtilInit( designSize: designSize, builder: (context) => Scaffold(......)` in flutter it was working fine.
> 
> How many times you use ScreenUtilInit() ?

i guess this is my mistakes, i created more than one screen util init in my project. it was working fine in flutter 2.10 but when i upgrade to flutter 3.0 this error appear.

my problem has solved, thanks for suggestion.
