### ISSUE TITLE
一个问题，按照文档来，在第一次build初始化报错

### ISSUE THREAD

**Issue by lixingqiao01** [OpenFlutter/flutter_screenutil#82]
```dart

void main() {
  sharedPreferencesUntil();
  return runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {


    ScreenUtil.instance =
    ScreenUtil(width: 750, height: 1334, allowFontScaling: true)
      ..init(context);

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("ss"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
            FlatButton(
              child: Text("open new route"),
              textColor: Colors.blue,
              onPressed: (){
                Navigator.push(context, MaterialPageRoute(builder: (context) {
                  return NewRoute();
                },fullscreenDialog: true));
              },
            )
          ],
        ),
      ),
      floatingActionButton: FancyFab(),
    );
  }
}

```

### 错误提示  
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building MyApp(dirty):
flutter: MediaQuery.of() called with a context that does not contain a MediaQuery.
flutter: No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
flutter: This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
flutter: a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
flutter: The context used was:
flutter:   MyApp(dirty)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:722:5)
flutter: #1      ScreenUtil.init (package:flutter_screenutil/flutter_screenutil.dart:41:44)
flutter: #2      MyApp.build (package:flutter_demo/main.dart:25:9)
flutter: #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4009:28)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #10     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:998:16)
flutter: #11     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:969:5)
flutter: #12     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:915:17)
flutter: #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2328:19)
flutter: #14     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:914:13)
flutter: #15     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:795:7)
flutter: #16     runApp (package:flutter/src/widgets/binding.dart:845:7)
flutter: #17     main (package:flutter_demo/main.dart:14:10)
flutter: #18     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
flutter: #23     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
flutter: #24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
flutter: #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
flutter: (elided 4 frames from package dart:async)
```

**Comment by lizhuoyuan** [comment]
初始化的位置错了。
不在 MyApp  
放在 MyHomePage 中
